### ISSUE TITLE
Problem with data-test

### ISSUE THREAD

**Issue by PhilippeNoel1** [3D-e-Chem/kripo#1]
* Kripo version: 1.0.0
* Python version: 3.6
* Operating System: Ubuntu 18.04.1 LTS

### Description
I'm trying to test kripo with the data-set given in the Usage part of the README.

### What I Did

```
(kripo) pnoel at margotte in ~/tmp/kripo on master*
$ wget http://ligand-expo.rcsb.org/dictionaries/all-sdf.sdf.gz
(kripo) pnoel at margotte in ~/tmp/kripo on master*
$ kripo ligands import all-sdf.sdf.gz ligand-expo.db
```

Got the following error :
```
Traceback (most recent call last):
  File "/home/pnoel/miniconda3/envs/kripo/bin/kripo", line 11, in <module>
    load_entry_point('kripo==1.0.0', 'console_scripts', 'kripo')()
  File "/home/pnoel/miniconda3/envs/kripo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pnoel/miniconda3/envs/kripo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/pnoel/miniconda3/envs/kripo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/pnoel/miniconda3/envs/kripo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pnoel/miniconda3/envs/kripo/lib/python3.6/site-packages/kripo-1.0.0-py3.6.egg/kripo/cli.py", line 17, in <module>
    from .pharmacophore import Feature, Pharmacophore
ModuleNotFoundError: No module named 'kripo.pharmacophore'

```

**Comment by PhilippeNoel1** [comment]
Yes it's work now. Thanks for the fast reply :)
